
ldoc -c ./config.ld ../../rts/Lua/LuaSyncedCtrl.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaUnsyncedCtrl.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaSyncedRead.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaUnsyncedRead.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaSyncedMoveCtrl.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaHandle.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaHandleSynced.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaVFS.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaVAO.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaVAOImpl.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaVBO.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaVBOImpl.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaOpenGL.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaZip.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaRules.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaMetalMap.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaShaders.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaFBOs.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaRBOs.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaMathExtra.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaBitOps.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstGame.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstEngine.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstPlatform.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstCMD.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstCMDTYPE.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstCOB.cpp
ldoc -c ./config.ld ../../rts/Lua/LuaConstGL.cpp
Move-Item -Path .\BitOps.md -Destination .\Autogenerated\BitOps.lua
Move-Item -Path .\Engine.md -Destination .\Autogenerated\Engine.lua
Move-Item -Path .\Game.md -Destination .\Autogenerated\Game.lua
Move-Item -Path .\GL.md -Destination .\Autogenerated\GL.lua
Move-Item -Path .\LuaHandle.md -Destination .\Autogenerated\LuaHandle.lua
Move-Item -Path .\LuaHandleSynced.md -Destination .\Autogenerated\LuaHandleSynced.lua
Move-Item -Path .\LuaRules.md -Destination .\Autogenerated\LuaRules.lua
Move-Item -Path .\MathExtra.md -Destination .\Autogenerated\MathExtra.lua
Move-Item -Path .\OpenGL.md -Destination .\Autogenerated\OpenGL.lua
Move-Item -Path .\Platform.md -Destination .\Autogenerated\Platform.lua
Move-Item -Path .\RBO.md -Destination .\Autogenerated\RBO.lua
Move-Item -Path .\SyncedCtrl.md -Destination .\Autogenerated\SyncedCtrl.lua
Move-Item -Path .\UnsyncedCtrl.md -Destination .\Autogenerated\UnsyncedCtrl.lua
Move-Item -Path .\UnsyncedRead.md -Destination .\Autogenerated\UnsyncedRead.lua
Move-Item -Path .\VAO.md -Destination .\Autogenerated\VAO.lua
Move-Item -Path .\VBO.md -Destination .\Autogenerated\VBO.lua